const test = require('tape')

test('should throw when not authorized', (t) => {
  // TODO: write a test that fails due to the bug in
  // Calculator.divide()
  t.end()
})
